// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS0UWf_Us_oCAjaq762umTN7InYq-sMHU',
    appId: '1:533192187427:web:4bdfa10cb8943d691c5b96',
    messagingSenderId: '533192187427',
    projectId: 'aerofly-ed8db',
    authDomain: 'aerofly-ed8db.firebaseapp.com',
    storageBucket: 'aerofly-ed8db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS0UWf_Us_oCAjaq762umTN7InYq-sMHU',
    appId: '1:533192187427:android:4bdfa10cb8943d691c5b96',
    messagingSenderId: '533192187427',
    projectId: 'aerofly-ed8db',
    storageBucket: 'aerofly-ed8db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS0UWf_Us_oCAjaq762umTN7InYq-sMHU',
    appId: '1:533192187427:ios:fc0255d2a84f10f51c5b96',
    messagingSenderId: '533192187427',
    projectId: 'aerofly-ed8db',
    storageBucket: 'aerofly-ed8db.firebasestorage.app',
    iosBundleId: 'com.example.aerofly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS0UWf_Us_oCAjaq762umTN7InYq-sMHU',
    appId: '1:533192187427:ios:fc0255d2a84f10f51c5b96',
    messagingSenderId: '533192187427',
    projectId: 'aerofly-ed8db',
    storageBucket: 'aerofly-ed8db.firebasestorage.app',
    iosBundleId: 'com.example.aerofly',
  );
} 